# Generated by Django 2.2.24 on 2021-11-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_profile_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration', models.DurationField()),
                ('description', models.TextField(max_length=1000)),
                ('of_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Profile')),
            ],
        ),
    ]
