# Generated by Django 2.2.24 on 2021-11-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_new_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
