# Generated by Django 2.2.24 on 2021-12-02 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Geocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=20, default=0, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=20, default=0, max_digits=30)),
                ('raw', models.TextField(blank=True, max_length=500)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geocode', to='product.Profile')),
            ],
        ),
    ]
